apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-db 
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 16Mi
  selector:
    matchLabels:
      app: postgresdb